# Generated by Django 4.2.20 on 2025-04-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='clerk_id',
            new_name='clerkId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image_url',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
